name: daily-pipeline

on:
  schedule:
    - cron: '15 05 * * *'   # 05:15 UTC daily
  workflow_dispatch: {}      # manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}  # let pytest import local modules
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: python -m pip install --upgrade pip
      - run: pip install pandas requests fastparquet matplotlib pytest

      - name: Run pytest
        run: pytest -q

      - name: Ingest
        run: python ingest.py
      - name: Transform
        run: python transform.py
      - name: Quality
        run: python quality.py
      - name: Storage
        run: python storage.py

      - name: Configure matplotlib backend
        run: |
          python - <<'PY'
          import matplotlib
          matplotlib.use("Agg")
          print("Matplotlib backend:", matplotlib.get_backend())
          PY

      - name: Build dashboard
        run: python dashboard.py

      - name: Upload artifact (docs/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4